### ISSUE TITLE
Opendr not getting installed to virtual environment

### ISSUE THREAD

**Issue by sudiptabiswas22** [polmorenoc/opendr#7]
Can you please write down the detailed steps including every command? I used the following commands and apparently opendr is not getting installed in my virtual env.
sudo git clone "https://github.com/polmorenoc/opendr.git"
cd opendr
cd opendr
sudo python setup.py install
![Screenshot from 2019-04-03 16-47-18](https://user-images.githubusercontent.com/25134017/55475085-903f5780-5630-11e9-9651-d66c726b6c7e.png)

**Comment by SpirinEgor** [comment]
I suppose the problem, that you install library for python 3 in environment for python 2

**Comment by Dawars** [comment]
If this is no longer relevant, please close the issue.

Otherwise I use this command to install both **chumpy** and **opendr**:
```
pip3 install git+https://github.com/polmorenoc/opendr/#subdirectory=chumpy 
                                git+https://github.com/polmorenoc/opendr/#subdirectory=opendr
```
